#!/bin/bash
# SELECTION Menu for uSvxCard  
#
#  F4ICR&F5SWB&F8ASB  21/11/2021
#
HEIGHT=15
WIDTH=40
PATH_SCRIPT='/opt/uSvxCard/callconfig.py'

entrercall()
{
call=$(whiptail --inputbox "Enter your callsign ?" 8 39 GXXXX --title "CALLSIGN" 3>&1 1>&2 2>&3)
exitstatus=$?

if [ $exitstatus = 0 ]; then
    echo "Callsign: " $call
    entrerdept
else
    echo "Cancel"; 
    spot
fi
}
entrerdept()
{
dept=$(whiptail --inputbox "Enter your departement ?" 8 39 XX --title "DEPARTEMENT" 3>&1 1>&2 2>&3)

exitstatus=$?

if [ $exitstatus = 0 ]; then
    echo "Departement: " $dept
    entrerband
else
    echo "Cancel"; break;
    entrercall
fi
}

entrerband()
{
band=$(whiptail --title "Type of HOTSPOT" --radiolist \
"Choose the type of HOTSPOT?" 15 60 8 \
"U" "UHF" ON \
"V" "VHF" OFF \
"H" "HOTSPOT" OFF \
"T" "TRANSPONDER" OFF \
"R" "REPEATER" OFF \
"10M" "SIMPLEX LINK 10M" OFF \
"T10M" "TRANSPONDER WITH 10M" OFF \
"S" "SPECIAL" OFF 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then
    arg1="--dept $dept"
    arg2="--call $call"
    arg3="--band $band"

echo $arg1
echo $arg2
echo $arg3

echo "python3 /opt/uSvxCard/callconfig.py $arg1 $arg2 $arg3"
python3 $PATH_SCRIPT $arg1 $arg2 $arg3

else
    echo "Vous avez annulé";break;
    entrerdept
fi
}



while : ; do

choix=$(whiptail --title "MicroSvxCard Menu 1.1 "  --menu "                    >> Make your choice " 40 70 31 \
1 "  Restart Spotnik in Parrot mode '95'" \
2 "  Restart Spotnik on the RRF '96'" \
3 "  Restart Spotnik on the FON Room '97'" \
4 "  Restart Spotnik on the TEC Room '98'" \
5 "  Restart Spotnik on the INT Room '99'" \
6 "  Restart Spotnik on the BAV Room '100'" \
7 "  Restart Spotnik on the LOC Room '101'" \
8 "  Restart Spotnik on the EXP Room '102'" \
9 "  Restart Spotnik on EchoLink '103'" \
10 "  Restart Spotnik on Regional '104'" \
11 "  Show the LOG Spotnik 'CTRL C' to quit" \
12 "  Edit Svxlink.cfg (configuration for all rooms)" \
13 "  Edit Svxlink.el  (configuration for ECHOLINK) " \
14 "  Edit the ModuleEchoLink.conf (configuration password)" \
15 "  Edit the airports for the weather" \
16 "  MC Midnight Commander" \
17 "  Configuration of Wifi wpa_supplicant.conf" \
18 "  Configuration of the sound card with Alsamixer" \
19 "  Configuration mail for the function of the propagation monitor" \
20 "  Configuration of the uDraCard card " \
21 "  Configuration of Spotnik (Callsign, Departement, Band) " \
22 "  Configuration Dwagent " \
23 "  Activation / Deactivation of RAPTOR Mode " \
24 "  Activation / Deactivation of NEXTION Screen " \
25 "  Activation / Deactivation of the Room Timer " \
26 "  Activation / Deactivation of the DTMF " \
27 "  Start / Stop SvxControl and SvxLink" \
28 "  Complete restart of the system "  \
29 "  Complete halt of the system " 3>&1 1>&2 2>&3)


exitstatus=$?

#recovering the choice
#exitstatus=$?
if [ $exitstatus = 0 ]; then
    echo "your choice :" $choix
else
    echo "Cancel the choice."; break;
fi



# case : action en fonction du choix

case $choix in

1)
/etc/spotnik/restart.default ;;

2)
/etc/spotnik/restart.rrf ;;

3)
/etc/spotnik/restart.fon ;;

4)
/etc/spotnik/restart.tec ;;

5)
/etc/spotnik/restart.int ;;

6)
/etc/spotnik/restart.bav ;;

7)
/etc/spotnik/restart.loc ;;

8)
/etc/spotnik/restart.exp ;;

9)
/etc/spotnik/restart.el ;;

10)
/etc/spotnik/restart.reg ;;

11)
/etc/spotnik/view_svx ;;

12)
mcedit /etc/spotnik/svxlink.cfg ;;

13)
mcedit /etc/spotnik/svxlink.el ;;

14)
mcedit /etc/spotnik/svxlink.d/ModuleEchoLink.conf ;;

15)
mcedit /etc/spotnik/svxlink.d/ModuleMetarInfo.conf ;;

16)
mc /etc/spotnik ;;

17)
mcedit /etc/wpa_supplicant/wpa_supplicant.conf ;;

18)
alsamixer && alsactl store ;;

19)
fetchsetup ;;

20)
sh /opt/uDraCard/uDraCard_config.sh ;;

21)
entrercall ;;

22)
sh /usr/share/dwagent/native/configure ;;

23)
sh /opt/RRFRaptor/RRFRaptor.sh ;;

24)
sh /opt/uSvxCard/hmi.sh ;;

25)
echo "111#" > /tmp/dtmf_vhf
echo "111#" > /tmp/dtmf_uhf ;;

26)
echo "999#" > /tmp/dtmf_vhf
echo "999#" > /tmp/dtmf_uhf ;;

27)
sh /opt/uSvxCard/svxcontrol.sh ;;

28)
sudo reboot ;;

29)
sudo halt ;;

esac

done
exit 0



